/*
 * File: app/store/userInfos.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.store.userInfos', {
    extend: 'Ext.data.Store',
    alias: 'store.userinfos',

    requires: [
        'MStore.model.userInfo',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'userInfos',
            model: 'MStore.model.userInfo',
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});