/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'GenderType',
        'userInfo'
    ],
    stores: [
        'genderTypes',
        'userInfos'
    ],
    views: [
        'admin.SinginWin',
        'admin.SignupWin',
        'admin.Signin',
        'profile.userProfile'
    ],
    name: 'MStore',

    launch: function() {
        Ext.create('MStore.view.admin.Signin', {renderTo: Ext.getBody()});
    }

});
