/*
 * File: app/view/profile/userProfile.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.profile.userProfile', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.profile.userprofile',

    requires: [
        'MStore.view.profile.userProfileViewModel'
    ],

    viewModel: {
        type: 'profile.userprofile'
    },
    height: 250,
    width: 400

});