/*
 * File: app/view/admin/SignupWin.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.admin.SignupWin', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.admin.signupwin',

    requires: [
        'MStore.view.admin.SignupWinViewModel',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'admin.signupwin'
    },
    height: 250,
    id: 'up_FSignUP',
    width: 400,
    layout: 'center',

    items: [
        {
            xtype: 'form',
            height: 518,
            width: 367,
            bodyPadding: 10,
            title: 'Sign Up',
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'top',
                    height: 101,
                    layout: 'center',
                    items: [
                        {
                            xtype: 'image',
                            height: 78,
                            width: 89,
                            src: 'ico/user.png'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    dock: 'bottom',
                    height: 53,
                    width: 367,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'up_BBack',
                            width: 182,
                            text: 'Back'
                        },
                        {
                            xtype: 'button',
                            id: 'up_BSubmit',
                            width: 190,
                            text: 'Submit'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'up_fname',
                    fieldLabel: 'First Name'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'up_lname',
                    fieldLabel: 'Last Name'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'up_email',
                    fieldLabel: 'Email',
                    inputType: 'email'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    id: 'up_birthday',
                    fieldLabel: 'Birthday'
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    id: 'up_gender',
                    fieldLabel: 'Gender',
                    displayField: 'typeID',
                    queryMode: 'local',
                    store: 'genderTypes',
                    valueField: 'typeID'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'up_pass',
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'up_repass',
                    fieldLabel: 'Re-Passwrod',
                    inputType: 'password'
                }
            ]
        }
    ]

});