/*
 * File: app/view/admin/SignupWinViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.6.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MStore.view.admin.SignupWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.admin.signupwin',

    onUp_BBackClick: function(button, e, eOpts) {
        var singup = Ext.create('MStore.view.admin.Signin',{});
        singup.show();
        Ext.getCmp('up_FSignUP').destroy();
    },

    onUp_BSubmitClick: function(button, e, eOpts) {
        var fname = Ext.getCmp('up_fname').value;
        var lname = Ext.getCmp('up_lname').value;
        var email = Ext.getCmp('up_email').value;
        var gender = Ext.getCmp('up_gender').value;
        var password = Ext.getCmp('up_pass').value;
        var repassword = Ext.getCmp('up_repass').value;

        var birthday = Ext.getCmp('up_birthday').getValue();
        var date = new Date(birthday);
        birthday = Ext.Date.format(date, 'd-m-Y');

        console.log( fname + email + password + birthday + gender);

        // ------------------------------------ Server -------------------------------------------------

        Ext.Ajax.request({
            url: 'php/aapi.php',
            method: 'POST',
            params: {'request': 'create','name': fname +' '+ lname, 'email': email, 'birthday': birthday, 'gender': gender, 'pass': password },
            headers:
            {
                'Content-Type': 'application/x-www-form-urlencoded'
            },

            success: function(response, opts) {
                var getdataserver = response.responseText;
                if(getdataserver == 'false')
                {
                    Ext.getCmp('up_status').setText('Status: The Email already exists');
                }
                else
                {
                    var singup = Ext.create('MStore.view.admin.Signin',{});
                    singup.show();
                    Ext.getCmp('up_FSignUP').destroy();
                }
                console.log('i am work');
            },

            failure: function(response, opts) {
                console.log('server-side failure with status code ' + response.status);
            }
        });

    }

});
